### ISSUE TITLE
support aeson >= 2

### ISSUE THREAD

**Issue by kisonecat** [lf-/lti13#4]
I'd like to be able to use `li13` with `aeson >= 2`.

To make this possible, I replaced some `Text` with `Aeson.Key` in a few places in a80b1e0b24c19cc4304306d13acf3366eacdb81a which seems necessary to provide compatibility with `aeson >= 2`.  I imagine there are cleaner ways of handling this.

In any case, I wasn't able to get [yesod-auth-lti13](https://github.com/lf-/lti13/tree/main/yesod-auth-lti13) to work with these changes, hence my opening an issue rather than submitting a PR.

**Comment by lf-** [comment]
I'll look into this when I have time. Thanks for the pointers!

**Comment by lf-** [comment]
Gosh, sorry it took so long. I'm going to fix this this evening.

**Comment by kisonecat** [comment]
Oh no need to apologize -- I just am very appreciative of your having put this whole thing together!

**Comment by lf-** [comment]
Hi! I've made a pull request and from testing it against the LTI reference implementation I believe it to work. Can you check if it works for you?

**Comment by lf-** [comment]
Closed and 0.3.0.0 of both lti13 and yesod-auth-lti13 have been published. Let me know if you have any issues!

**Comment by kisonecat** [comment]
This is working great -- thank you so much!
